[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "cocat"
version = "0.3.1"
description = "CRDT-based tscat"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "David Brochart", email = "david.brochart@gmail.com" },
]
readme = "README.md"
keywords = [
  "crdt",
]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
]

dependencies = [
  "pycrdt >=0.12.40,<0.13.0",
  "pydantic >=2.12.0,<3.0.0",
  "typing_extensions >=4.15.0,<5.0.0; python_version<'3.11'",
  "wiredb >=0.5.0,<0.6.0",
]

[dependency-groups]
test = [
  "mypy",
  "ruff",
  "pytest",
  "coverage",
  "trio",
  "requests",
]
docs = [
  "mkdocs",
  "mkdocs-material",
  "mkdocstrings[python]",
]

[project.optional-dependencies]
server = [
  "cyclopts >=4.0.0,<5.0.0",
  "wire-file >=0.5.0,<0.6.0",
  "wire-websocket >=0.5.0,<0.6.0",
  "fastapi >=0.120.3,<0.121.0",
  "fastapi-users[sqlalchemy] >=15.0.1,<16.0.0",
  "anycorn >=0.18.2,<0.19.0",
  "aiosqlite >=0.21.0,<0.22.0",
]
client = [
  "wire-file >=0.5.0,<0.6.0",
  "wire-websocket >=0.5.0,<0.6.0",
  "httpx >=0.28.1,<0.29.0",
]

[project.scripts]
cocat = "cocat.cli:main"

[project.urls]
Homepage = "https://github.com/SciQLop/cocat"

[tool.uv.build-backend]
module-name = "cocat"
