name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install cocat
      run: |
        pip install . --group test

    - name: Check types
      run: |
        mypy src tests

    - name: Lint
      run: |
        ruff check src tests

    - name: Run tests
      if: ${{ !((matrix.python-version == '3.14') && (matrix.os == 'ubuntu')) }}
      run: pytest -v --color=yes

    - name: Run code coverage
      if: ${{ (matrix.python-version == '3.14') && (matrix.os == 'ubuntu') }}
      run: |
        coverage run -m pytest tests
        coverage report --show-missing --fail-under=100
